ADF/18BCE167_Practical-4_Project Folder/socialMediaApp/post/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('displayPost',views.displayPost,name="displayPost"),
    path('updatePost/<int:pk>',views.updatePost,name="updatePost"),
    path('createPost',views.createPost,name="createPost"),
    path('delete/<int:pk>',views.deletePost,name="deletePost"),
    path('myPost',views.myPost,name="myPost"),
]

ADF/18BCE167_Practical-4_Project Folder/socialMediaApp/socialMediaApp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from login import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('login.urls')),
    path('',include('post.urls')),

    path('signup/',views.signup,name="signup"),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='login.html'), name='logout'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
]

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

ADF/18BCE167_Practical-4_Project Folder/socialMediaApp/post/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    id=models.AutoField(primary_key=True)
    username=models.CharField(max_length=50)
    post=models.TextField()
    title=models.CharField(max_length=50)
    image = models.ImageField(upload_to='images/')
    file = models.FileField(upload_to='files/')

ADF/18BCE167_Practical-4_Project Folder/socialMediaApp/post/forms.py
from django import forms
from .models import Post

class createPostForm(forms.ModelForm):
  post=forms.CharField(label="Post",widget = forms.Textarea)
  image = forms.ImageField(label="Image",required=False)
  title=forms.CharField(label="Title")
  file = forms.FileField(label="File",required=False)
  class Meta:
    model = Post
    fields=['title','post','image','file']

ADF/18BCE167_Practical-4_Project Folder/socialMediaApp/post/views.py
from django.shortcuts import render,redirect
from .models import Post
from .forms import createPostForm
from socialMediaApp import settings
# Create your views here.


def displayPost(req):
    post=Post.objects.all()
    username=""
    if req.user:
        username=req.user
    print(username)
    print(settings.MEDIA_ROOT)
    return render(req,'displayPost.html',{"posts":post,"username":username})

def createPost(req):
    if req.method == 'POST':
        form = createPostForm(req.POST,req.FILES)
        if form.is_valid():
            username = req.user
            posts = req.POST['post']
            title = req.POST['title']
            post=""
            try:
                image = req.FILES['image']
                try:
                    file = req.FILES['file']
                    post = Post(username=username,post=posts,title=title,image=image,file=file)
                except:
                    post = Post(username=username,post=posts,title=title,image=image)
            except:
                post = Post(username=username,post=posts,title=title)
            post.save()
            return redirect('displayPost')
    else:
        form = createPostForm()
        print(type(form))

    return render(req, 'createPost.html', {'form': form})


def updatePost(req, **primarykey):
    postId = primarykey['pk']
    post=list(Post.objects.filter(username=req.user,id=postId))[0]
    if req.method == 'POST':
        # form = createPostForm(req.POST,req.FILES)
        username = req.user
        title = req.POST['title']
        posts = req.POST['post']

        post = list(Post.objects.filter(username=username,
                    id=postId))[0]
        post.post=posts
        post.title=title
        try:
            image = req.FILES['image']
            post.image=image
        except:
            pass
        post.save()
        return redirect('displayPost')
    else:
        form = createPostForm()
        print(type(form))

    return render(req,'updatePost.html',{"post":post})

def deletePost(req, **primarykey):
    postId=primarykey['pk']
    Post.objects.filter(username=req.user,id=postId).delete()
    return redirect('displayPost')

def myPost(req):
    post=Post.objects.filter(username=req.user)
    return render(req,'myPost.html',{"posts":post})

ADF/18BCE167_Practical-4_Project Folder/socialMediaApp/post/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" crossorigin="anonymous">
    
    
    {% block style %}
    {% endblock style %}
</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div> 
</body>
</html>

ADF/18BCE167_Practical-4_Project Folder/socialMediaApp/post/templates/createPost.html
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for message in messages %}
        <strong>Message:</strong> {{ message }}
    {% endfor %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

ADF/18BCE167_Practical-4_Project Folder/socialMediaApp/post/templates/displayPost.html
<html>
    <head>
        <title>Post</title> 
    </head>
    <body>
        {% if not username%}
            <button type="button" class="btn btn-primary" id="login">Login</button>
            <button type="button" class="btn btn-primary" id="signup">Signup</button><br><br>
        {% else %}
            <button type="button" class="btn btn-primary" id="create">Add Post</button>
            <button type="button" class="btn btn-primary" id="myPost">My Post</button><br><br>
            <button type="button" class="btn btn-primary" id="logout">Logout</button><br><br>
        {% endif %}

        <!-- {{username}} -->
        {% for post in posts %}
            <br>
            <b>{{post.username}}</b>&nbsp;&nbsp;&nbsp;
            
            {% ifequal post.username|stringformat:"s"  username|stringformat:"s" %}
            
                <button type="button" class="btn btn-primary btn-sm" id="update" onclick="update('{{post.id}}')">Update</button>
                <button type="button" class="btn btn-primary btn-sm" id="delete" onclick="delet('{{post.id}}')">Delete</button><br>
            {% else %}<br>
            {% endifequal %}    
            Title : &nbsp;&nbsp;&nbsp;  
            {{post.title}}<br>
            {% if post.image %}
                Image : &nbsp;&nbsp;&nbsp;
                <img src="{{post.image.url}}" alt="Post Image" width="500" height="333"/><br>
            {% endif %}

            Post : &nbsp;&nbsp;&nbsp;
            {{post.post}}<br>
        {% endfor %}
        </body>
</html>

{% if not username %}
    <script>
        document.getElementById('login').onclick=function(){
            location.href="{% url 'login' %}"
        };
        document.getElementById('signup').onclick=function(){
            location.href="{% url 'signup' %}"
        };
    </script>
{% else %}
    <script>
        document.getElementById('create').onclick=function(){
            location.href="{% url 'createPost' %}"
        };
        document.getElementById('myPost').onclick=function(){
            location.href="{% url 'myPost' %}"
        };
        document.getElementById('logout').onclick=function(){
            location.href="{% url 'logout' %}"
        };
    </script>
{% endif %}

<script>
    
    function update(id){
        window.location = "{% url 'updatePost' 1234 %}".replace(/1234/, id.toString());
    }
    function delet(id){
        window.location = "{% url 'deletePost' 1234 %}".replace(/1234/, id.toString());
    }
</script>

ADF/18BCE167_Practical-4_Project Folder/socialMediaApp/post/templates/myPost.html
<html>
    <head>
        <title>Post</title> 
    </head>
    <body>
        <button type="button" class="btn btn-primary" id="create">Add Post</button>
        <button type="button" class="btn btn-primary" id="back">Back</button>
        <button type="button" class="btn btn-primary" id="logout">Logout</button><br><br>
    
        
        {% for post in posts %}
        <br>
        <b>{{post.username}}</b>&nbsp;&nbsp;&nbsp;
            <button type="button" class="btn btn-primary btn-sm" id="update" onclick="update('{{post.id}}')">Update</button>
            <button type="button" class="btn btn-primary btn-sm" id="delete" onclick="delet('{{post.id}}')">Delete</button><br>
            Title : &nbsp;&nbsp;&nbsp;  
            {{post.title}}<br>
            {% if post.image %}
                Image : &nbsp;&nbsp;&nbsp;
                <img src="{{post.image.url}}" alt="Post Image" width="500" height="333"/><br>
            {% endif %}

            Post : &nbsp;&nbsp;&nbsp;
            {{post.post}}<br>
        {% endfor %}
        </body>
</html>

<script>
    document.getElementById('create').onclick=function(){
        location.href="{% url 'createPost' %}"
    };
    document.getElementById('back').onclick=function(){
        location.href="{% url 'displayPost' %}"
    };
    document.getElementById('logout').onclick=function(){
        location.href="{% url 'logout' %}"
    };
</script>

<script>
    
    function update(id){
        window.location = "{% url 'updatePost' 1234 %}".replace(/1234/, id.toString());
    }
    function delet(id){
        window.location = "{% url 'deletePost' 1234 %}".replace(/1234/, id.toString());
    }
</script>

ADF/18BCE167_Practical-4_Project Folder/socialMediaApp/post/templates/updatePost.html
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for message in messages %}
        <strong>Message:</strong> {{ message }}
    {% endfor %}
    <label for="title"> :: Enter Your Title Below ::</label><br>
    <input type="text" id="id_title" name="title" rows="4" cols="50" value="{{post.title}}"/><br><br>
    {% if post.image %}
        <img src="{{post.image.url}}" alt="Post Image" width="500" height="333"/><br/>
    {% endif %}
    <label for="image"> :: Update Image here ::</label><br>
    <input type="file" name="image" id="id_image"><br><br><br>
    
    <label for="post"> :: Enter Your Post Below :: </label><br>
    <textarea id="id_post" name="post" rows="4" cols="50">{{post.post}}</textarea><br><br>
    <input type="submit" value="Submit">
</form>